"""rename department

Revision ID: 80df75d270f0
Revises: fbba296de8fc
Create Date: 2024-04-02 13:13:35.525801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80df75d270f0'
down_revision = 'fbba296de8fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')

    # ### end Alembic commands ###
